### ISSUE TITLE
Readme - filepath doesn't match tap.py

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/tap-universal-file#25]
While reviewing https://github.com/MeltanoLabs/tap-universal-file/pull/18/files#diff-77aed8fa9914c5f46ed2fa0a9c005b566fa8b00f2ab6aff45305db9df30f1e65 I noticed the `filepath` in the Readme doesn't match `tap.py`'s description. We can address later

**Comment by sebastianswms** [comment]
Could you clarify? To me it looks like [the README](https://github.com/MeltanoLabs/tap-universal-file/blob/main/README.md?plain=1#L25) matches [`tap.py`](https://github.com/MeltanoLabs/tap-universal-file/blob/main/tap_universal_file/tap.py#L70-L71)

**Comment by visch** [comment]
hmm not sure
